version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend_VueJs/my-vue-app
      dockerfile: Dockerfile
    volumes:
      - ./Frontend_VueJs/my-vue-app:/app
      - ./Backend_Symfony/my-symfony-app/public/vue_dist:/app/dist
    working_dir: /app
    command: npm run build

  backend:
    build:
      context: ./Backend_Symfony/my-symfony-app
      dockerfile: Dockerfile
    volumes:
      - ./Backend_Symfony/my-symfony-app:/var/www
    working_dir: /var/www
    expose:
      - "9000"  
    depends_on:
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./Backend_Symfony/my-symfony-app/public:/var/www/public
      - ./Backend_Symfony/my-symfony-app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
